package by.epam.afc.controller.command;

public enum CommandType {
    LOGIN_COMMAND,
    LOGOUT_COMMAND,
    CHANGE_LOCALE,
    FORGOT_PASSWORD,
    REGISTER_COMMAND,
    TO_LOGIN_PAGE,
    TO_REGISTER_PAGE,
    TO_CONFIRM_PAGE,
    TO_SUBMIT_AD_PAGE,
    TO_MODERATOR_PAGE,
    TO_ADMINISTRATOR_PAGE,
    TO_MY_ANNOUNCEMENTS_PAGE,
    TO_BAN_PAGE,
    FIND_MY_ANNOUNCEMENTS,
    FIND_ANNOUNCEMENTS,
    SUBMIT_ANNOUNCEMENT,
    SHOW_ANNOUNCEMENT,
    CONFIRM_ACCOUNT
}
